[tox]
envlist = lint, type
isolated_build = true

[testenv]
skip_install = true
allowlist_externals = poetry
setenv =
    POETRY = {env:POETRY:poetry}
    PYTHONPATH = {toxinidir}/src
commands_pre =
    {env:POETRY} install

[testenv:lint]
commands =
    {env:POETRY} run ruff check src scripts
    {env:POETRY} run ruff format --check src scripts

[testenv:type]
commands =
    {env:POETRY} run mypy src scripts
